### ISSUE TITLE
Broker connection

### ISSUE THREAD

**Issue by xbmcnut** [javiergayala/MMM-mqtt#1]
I have it configured on a Pi2 connecting to an external broker. Screen says "MQTT data loading" but when I publish to ESP/Test with the topic 'Hello', nothing appears on the screen.

```
		{
			module: 'MMM-mqtt',
			position: 'bottom_left',
			header: 'Living Room Temperature', // This is optional
			config: {
				mqttServer: '10.0.2.8', //Connection string for the server to connect to (mqtt://localhost)
				loadingText: 'MQTT Data Loading...', //Text to display while waiting for data to load
				topic: 'ESP/Test/', //MQTT Topic to subscribe to on the server (sensors/temperature/livingroom)
				showTitle: 'true', //Boolean to show/hide a title (default: false)
				title: 'Test', //Title to show if showTitle is true
				interval: '', //Refresh interval, not including MQTT subscription deliveries. (default: 300000)
				postText: '', //Text to append after the data received from MQTT (default: '')
			}
		},
```
Have I got everything configured OK?

**Comment by marksev1** [comment]
Any news here? xbmcnut have you managed to get it working? (I want to know before I try on my own hehe)

**Comment by xbmcnut** [comment]
@marksev1 Sorry no, never got it to go. Connects to broker, that's about it.

**Comment by javiergayala** [comment]
I'm sorry for not responding sooner.  It's been a while since I've messed with this module.  I'm running an MQTT server local to this MM instance, and since it's behind my firewall I'm running it in a non-secure mode.  I'm not using any username/passwords or SSL encryption.  Here is an example of my config:

```javascript
{
	module: 'MMM-mqtt',
	position: 'top_right',
	header: 'Media Cab Temperature',
	config: {
		mqttServer: 'mqtt://localhost',
		topic: 'sensors/temperature/mediacab',
		postText: '°F'
	}
}
```

The main difference that stands out to me between my config and yours is that you only have the IP address listed under `mqttServer`.  It's missing the `mqtt://` URI Scheme.  Try changing it to:

```javascript
{
	module: 'MMM-mqtt',
	position: 'bottom_left',
	header: 'Living Room Temperature', // This is optional
	config: {
		mqttServer: 'mqtt://10.0.2.8', //Connection string for the server to connect to (mqtt://localhost)
		loadingText: 'MQTT Data Loading...', //Text to display while waiting for data to load
		topic: 'ESP/Test/', //MQTT Topic to subscribe to on the server (sensors/temperature/livingroom)
		showTitle: 'true', //Boolean to show/hide a title (default: false)
		title: 'Test', //Title to show if showTitle is true
		interval: '', //Refresh interval, not including MQTT subscription deliveries. (default: 300000)
		postText: '', //Text to append after the data received from MQTT (default: '')
	}
},
```

Also, I think that you may need to mess with the `topic` field as well.  If I recall correctly, you may need to use a wildcard if you want to subscribe to everything beneath `ESP/Test/`.  For example, if you have multiple topics beneath `ESP/Test/`, such as `ESP/Test/1/2` and `ESP/Test/2/2` you would then need to set your `topic` to `ESP/Test/**/*`.  That being said, I've never tried using this module with wildcards in the topic, so I'm not certain that it will work.  If you just want to test connectivity, I suggest setting the `topic` to subscribe to one specific topic, with no slashes at the end.

Hope this helps.

**Comment by marksev1** [comment]
Edit: I can confirm that it works. Nice job Javier!

**Comment by xbmcnut** [comment]
@marksev1 Could you kindly post your config? I can't get it to work with an external broker. It seems to connect to the broker but if I put `mqttServer: 'mqtt://10.0.2.8'`, I get a _can't connect to broker_ message multiple times on the screen. I've fired up my rig again today and updated both MagicMirror and PM2 so I'll have another go in the morning.

**Comment by marksev1** [comment]
i tried it on the same machine as the broker i just did 'mqtt://localhost:1883" and it worked...But if it worked this way I think it should also work if the mqtt broker was on another machine on the local network. Maybe you forgot to specify the port on which mosquitto is running.

I used the same example config like Javier to test.

**Comment by javiergayala** [comment]
@xbmcnut are you able to connect to the broker at all from the machine that is running MM?  You can use netcat to perform a basic connection test from the computer running MM to see if there is a connectivity issue:

```bash
nc -v 10.0.2.8 1883
```

You should either get a successful connection, or a timeout.  If you get a successful connection, then you will have to start digging deeper into the mqtt session, such as ensuring that you have the appropriate server and client configuration to allow the subscription between the two hosts.  When I was troubleshooting my connections I used the `mosquitto_sub` client in my attempts to debug my connections between my MagicMirror computer and the broker.

Another option that you may need to explore if you already have a local mqtt server is to configure the local mqtt server as a bridge to the external mqtt server.  For example, I have an external mqtt server on a cloud server that I use with OwnTracks.  My local mqtt server at home is configured as a bridge to the external mqtt server.  This allows me to subscribe to the OwnTracks topics locally as if the local server were the external mqtt server that I use for OwnTracks.  The external mqtt server uses mqtt over SSL as well as user authentication, whereas my local mqtt server does not.  The bridge configuration takes care of the SSL and authentication between the local and external mqtt servers so that my local mqtt clients (like MagicMirror) don't need to be concerned with it.

Hope this helps.

**Comment by xbmcnut** [comment]
Don't know why I didn't think to check, but it seems MQTT is not running on my build. From MMM-mqtt I ran `npm install` and everything seemed to install OK. But when I modify the config to connect to localhost, I get the on-screen "_MQTT server is offline_" message. Using MQTT.fx, if I try and connect to that IP address, no connection either.

P.S The command nc -v 10.0.2.8 1883 returned successful but that won't mean much if the MQTT components on my MM server aren't running. :) Any clues as to how I debug the MQTT server?

**Comment by javiergayala** [comment]
You don't necessarily have to run a local mqtt server.  You should be able to connect to an external server as well.  In my particular case since I was already running a local mqtt server, it was easiest for me to setup a bridge to an external mqtt server so that I could see the topics from both instances.  However if you have no other need for a local mqtt server, then in theory you should be able to connect to the external mqtt server at `10.0.2.8`.  (I say in theory because I've only ever used localhost with this module.)

If you do need a local mqtt server, then it sounds like you either don't have one installed or it's not running.  I've only ever used the mosquitto mqtt server for which I used various How-to's that I found on the web.  If you just want to connect to the external mqtt server, then you need a client on the computer running MagicMirror that you can use to troubleshoot your connection.  You may need to run the external server in debug mode while you attempt connections from your MM computer.  That was what I ended up doing.  I had to run the mosquitto server in debug mode on my external cloud server, while using the `mosqutto_sub` client on my local MM computer in debug mode until I figured out what was keeping my connections from working.  (In my case it turned out to be an issue with using a self-signed SSL certificate.)

**Comment by xbmcnut** [comment]
Ah, making sense now. I thought that when you did the `npm install` it installed all dependencies but alas you need a client. I can get it to connect to my external broker, that is not an issue but of course, commands are not being subscribed to as there is no client. It seems the best route is to install Mosquitto? [http://randomnerdtutorials.com/how-to-install-mosquitto-broker-on-raspberry-pi/](http://randomnerdtutorials.com/how-to-install-mosquitto-broker-on-raspberry-pi/) Can you confirm this is the best approach?

**Comment by xbmcnut** [comment]
OK. Installed `sudo apt-get install mosquitto mosquitto-clients`. Seems this is mandatory prior to the install of MMM-mqtt so it might pay to modify your instructions? The 'binding' does not happen if Mosquitto is installed afterwards and setting `mqttServer: 'mqtt://localhost'` returns an offline MQTT message. Running `npm install` in your directory after installing Mosquitto fixes this and everything is working now, at least with the local MQTT broker.

**Comment by xbmcnut** [comment]
P.S I can confirm it now also works with an external broker with mine now as `mqttServer: 'mqtt://10.0.2.8'` so having Mosquitto installed prior to the installation of MMM-mqtt is for sure a dependency.

**Comment by javiergayala** [comment]
Good point! I already had it installed before I started developing this extension, so including it in the instructions never even crossed my mind.  I've updated the `README.md` file with that detail.  Thanks!

**Comment by xbmcnut** [comment]
Thanks for that. Not sure if you need Mosquitto (broker) and can most likely get away with just installing just the clients? On another note, is it possible to add further topic to display or would I have to add another instance of MMM-mqtt in the config file and position that somewhere else on the screen?

**Comment by marksev1** [comment]
You can add it in the same position and it will add it below the older one (including the title), just tried that.

**Comment by xbmcnut** [comment]
Awesome, thank you. So just duplicate the config entry with a different topic and it will 'stack' the entities?

**Comment by xbmcnut** [comment]
All working now as long as you install a MQTT client package prior to installing MMM-mqtt. Installation instructions have been updated to reflect this.

**Comment by xbmcnut** [comment]
All working now as long as you install a MQTT client package prior to installing MMM-mqtt. Installation instructions have been updated to reflect this.
